/**
 * Standalone entry for /html-lib/markdown.js — `window.CockpitMarkdown`.
 *
 * Bundled SELF-CONTAINED (its own React copy, built by scripts/build-html-lib.mjs)
 * so any html app can render Cockpit-style Markdown regardless of the app's own
 * stack (global React 18 UMD, plain JS, ...). Exposes an imperative widget API
 * instead of a React component on purpose: mixing two React copies in one tree
 * breaks, a black-box DOM widget doesn't.
 *
 * The widget is the SAME composition the Explorer's markdown preview uses:
 * MarkdownRenderer + rehypeSourceLines + TocSidebar (docked sidebar, h1–h6,
 * scroll spy, collapsible) — one implementation, two consumers.
 *
 *   CockpitMarkdown.render(el, content, opts?)   // mount or update in place
 *   CockpitMarkdown.unmount(el)                  // dispose the widget
 *
 *   opts = {
 *     isDark?: boolean          // force theme; omit → follow `dark` class on <html>
 *     enableMath?: boolean      // KaTeX, default true
 *     toc?: boolean             // TocSidebar, default true (self-hides when no headings)
 *     onLinkClick?: (href) => boolean  // return true = consume the click
 *     labels?: { en?: TocLabels, zh?: TocLabels }  // override the built-in
 *                               // TOC microcopy ({ toc, expandToc, collapseToc })
 *   }
 *
 * The widget owns its scroll container (flex row: sidebar + scrollable pane),
 * so give the mount element a height (e.g. position:fixed;inset:0).
 *
 * i18n: the widget ships its OWN default en/zh microcopy inline (below) on a
 * bundle-private i18next instance — cockpit's global dictionary is not
 * involved (the build aliases `@cockpit/shared-i18n` → `i18next`, so bundled
 * components resolve to this same instance). The host app only signals the
 * LANGUAGE TYPE: initial guess from navigator, live changes via the
 * `cockpit:language-change` postMessage broadcast; wording is overridable per
 * render via opts.labels.
 *
 * Requires /html-lib/markdown.css (utilities + katex, generated by the same
 * script) and /html-lib/theme.css (semantic color vars) on the page.
 */
import { useRef } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { I18nextProvider } from 'react-i18next';
import i18n from 'i18next';
import { MarkdownRenderer } from '../MarkdownRenderer';
import { TocSidebar } from '../TocSidebar';
import { rehypeSourceLines } from '../rehypeSourceLines';

interface TocLabels {
  toc?: string;
  expandToc?: string;
  collapseToc?: string;
}

// The widget's own microcopy — the only strings this bundle ships.
const DEFAULT_LABELS: Record<'en' | 'zh', Required<TocLabels>> = {
  en: { toc: 'TOC', expandToc: 'Expand TOC', collapseToc: 'Collapse TOC' },
  zh: { toc: '目录', expandToc: '展开目录', collapseToc: '收起目录' },
};

if (!i18n.isInitialized) {
  i18n.init({
    resources: {
      en: { translation: { editor: DEFAULT_LABELS.en } },
      zh: { translation: { editor: DEFAULT_LABELS.zh } },
    },
    lng: 'en',
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
  });
}

// Match the app's language resolution (workspace I18nProvider): navigator for
// the initial guess, then follow the host's broadcast on change.
i18n.changeLanguage(navigator.language.startsWith('zh') ? 'zh' : 'en');
window.addEventListener('message', (e) => {
  if (e.data?.type === 'cockpit:language-change' && e.data.lang) {
    if (i18n.language !== e.data.lang) i18n.changeLanguage(e.data.lang);
  }
});

interface RenderOpts {
  isDark?: boolean;
  enableMath?: boolean;
  toc?: boolean;
  onLinkClick?: (href: string) => boolean;
  labels?: Partial<Record<'en' | 'zh', TocLabels>>;
}

function applyLabels(labels: RenderOpts['labels']) {
  if (!labels) return;
  for (const lang of ['en', 'zh'] as const) {
    if (labels[lang]) {
      i18n.addResourceBundle(lang, 'translation', { editor: labels[lang] }, true, true);
    }
  }
}

const SOURCE_LINE_PLUGINS = [rehypeSourceLines];

function Widget({ content, opts, dark }: { content: string; opts: RenderOpts; dark: boolean }) {
  const scrollRef = useRef<HTMLDivElement>(null);
  return (
    // .cockpit-md-widget scopes the preflight stand-in (md-lib.css @layer base)
    // to the WHOLE widget incl. TocSidebar — its buttons assume Tailwind
    // preflight, which the standalone css deliberately doesn't ship.
    <div className="cockpit-md-widget flex h-full">
      {(opts.toc ?? true) && <TocSidebar content={content} containerRef={scrollRef} />}
      <div ref={scrollRef} className="flex-1 overflow-y-auto">
        <div className="cockpit-md">
          <MarkdownRenderer
            content={content}
            isDark={dark}
            enableMath={opts.enableMath}
            rehypePlugins={SOURCE_LINE_PLUGINS}
            onLinkClick={opts.onLinkClick}
          />
        </div>
      </div>
    </div>
  );
}

interface Mount {
  root: Root;
  content: string;
  opts: RenderOpts;
}

const mounts = new Map<Element, Mount>();

const htmlIsDark = () => document.documentElement.classList.contains('dark');

function renderMount(m: Mount) {
  m.root.render(
    // react-i18next only binds to an instance through a Provider — without
    // it, useTranslation falls back to an empty default instance and
    // TocSidebar labels render as raw keys.
    <I18nextProvider i18n={i18n}>
      <Widget content={m.content} opts={m.opts} dark={m.opts.isDark ?? htmlIsDark()} />
    </I18nextProvider>,
  );
}

// One shared observer: widgets without an explicit isDark follow the theme.css
// convention (`dark` class on <html>) and live-update on toggle.
let observer: MutationObserver | null = null;
function ensureThemeObserver() {
  if (observer) return;
  observer = new MutationObserver(() => {
    for (const m of mounts.values()) {
      if (m.opts.isDark === undefined) renderMount(m);
    }
  });
  observer.observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
}

function render(el: Element, content: string, opts: RenderOpts = {}) {
  applyLabels(opts.labels);
  let m = mounts.get(el);
  if (!m) {
    m = { root: createRoot(el), content, opts };
    mounts.set(el, m);
  } else {
    m.content = content;
    m.opts = opts;
  }
  ensureThemeObserver();
  renderMount(m);
}

function unmount(el: Element) {
  const m = mounts.get(el);
  if (!m) return;
  m.root.unmount();
  mounts.delete(el);
}

declare global {
  interface Window {
    CockpitMarkdown: { render: typeof render; unmount: typeof unmount };
  }
}

window.CockpitMarkdown = { render, unmount };
