import type { MetadataRoute } from 'next';
import { locales } from '@/lib/i18n';
import { posts } from '@/content/posts';
import { getAvailablePages } from '@/content/docs/sidebar';
import changelog from '@/data/changelog.json';
import docsLastmod from '@/content/docs/lastmod.json';

const SITE_URL = 'https://opencockpit.dev';

// Required for `output: 'export'` (Cloudflare Pages static export).
export const dynamic = 'force-static';

/**
 * Sitemap covering both locales for the homepage, docs, changelog, and blog.
 *
 * Each route emits hreflang `alternates` so Google groups the en/zh variants
 * as the same canonical resource — critical for our bilingual content.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const docsPages = getAvailablePages();

  // `lastmod` has to be honest or Google stops trusting the whole sitemap, so
  // every date below is derived from real content: the newest blog post, the
  // newest GitHub release, or the last commit that touched a docs file
  // (`content/docs/lastmod.json`, regenerated by `npm run lastmod`).
  const newestPost = posts.reduce((max, p) => (p.date > max ? p.date : max), '');
  const newestRelease = changelog.reduce(
    (max, r) => (r.publishedAt > max ? r.publishedAt : max),
    '',
  );
  const newestAnything = newestPost > newestRelease ? newestPost : newestRelease;
  const newestDoc = Object.values(docsLastmod as Record<string, string>).reduce(
    (max, d) => (d > max ? d : max),
    '',
  );

  const staticRoutes: { route: string; lastModified: string; priority: number }[] = [
    // The homepage reflects whatever shipped most recently, in either stream.
    { route: '', lastModified: newestAnything, priority: 1 },
    { route: '/changelog', lastModified: newestRelease, priority: 0.6 },
    { route: '/blog', lastModified: newestPost, priority: 0.8 },
    // `/docs/` is a real index page (it links every docs page), not the
    // redirect stub it used to be, so it belongs in the sitemap.
    { route: '/docs', lastModified: newestDoc, priority: 0.8 },
  ];

  const entries: MetadataRoute.Sitemap = [];

  for (const { route, lastModified, priority } of staticRoutes) {
    for (const locale of locales) {
      entries.push({
        url: `${SITE_URL}/${locale}${route}/`,
        lastModified,
        changeFrequency: 'weekly',
        priority,
        alternates: {
          languages: Object.fromEntries(
            [
              ...locales.map((l) => [l, `${SITE_URL}/${l}${route}/`]),
              ['x-default', `${SITE_URL}/en${route}/`],
            ],
          ),
        },
      });
    }
  }

  // Canonical documentation URLs (one per locale and available sidebar page).
  for (const page of docsPages) {
    for (const locale of locales) {
      entries.push({
        url: `${SITE_URL}/${locale}/docs/${page.slug}/`,
        lastModified: (docsLastmod as Record<string, string>)[page.slug] ?? newestAnything,
        changeFrequency: 'monthly',
        priority: 0.7,
        alternates: {
          languages: Object.fromEntries([
            ...locales.map((l) => [l, `${SITE_URL}/${l}/docs/${page.slug}/`]),
            ['x-default', `${SITE_URL}/en/docs/${page.slug}/`],
          ]),
        },
      });
    }
  }

  // Per-post URLs (one per locale).
  for (const post of posts) {
    for (const locale of locales) {
      entries.push({
        url: `${SITE_URL}/${locale}/blog/${post.slug}/`,
        lastModified: post.date,
        changeFrequency: 'monthly',
        priority: 0.7,
        alternates: {
          languages: Object.fromEntries(
            [
              ...locales.map((l) => [l, `${SITE_URL}/${l}/blog/${post.slug}/`]),
              ['x-default', `${SITE_URL}/en/blog/${post.slug}/`],
            ],
          ),
        },
      });
    }
  }

  return entries;
}
