/**
 * Standalone entry for /html-lib/pdf-viewer.js — `window.CockpitPdf`.
 *
 * Bundled SELF-CONTAINED (own React copy, built by scripts/build-html-lib.mjs)
 * so html apps get the same themed, virtualized PDF preview the Explorer uses
 * (FilePdfPreview: pdf.js canvas pages + thumbnail rail + zoom toolbar),
 * instead of the unthemable native PDFium iframe. Imperative widget API, same
 * rationale as CockpitMarkdown: a black-box DOM widget can't collide with the
 * host app's own React copy.
 *
 *   CockpitPdf.render(el, { cwd, path })   // mount or update in place
 *   CockpitPdf.unmount(el)
 *
 * Bytes stream from /api/files/read?cwd&path (Range-capable); the pdf.js
 * worker is the existing static asset /pdfjs/pdf.worker.min.mjs. Requires
 * /html-lib/pdf-viewer.css (utilities, generated by the same script) and
 * /html-lib/theme.css (semantic color vars) on the page; light/dark follows
 * the `dark` class on <html> via the token vars — no re-render needed.
 */
import { createRoot, type Root } from 'react-dom/client';
import { FilePdfPreview } from '../client/fileBrowser/FilePdfPreview';

interface PdfOpts {
  cwd: string;
  path: string;
}

const mounts = new Map<Element, Root>();

function render(el: Element, opts: PdfOpts) {
  let root = mounts.get(el);
  if (!root) {
    root = createRoot(el);
    mounts.set(el, root);
  }
  root.render(
    <div className="cockpit-pdf" style={{ height: '100%' }}>
      <FilePdfPreview cwd={opts.cwd} path={opts.path} />
    </div>,
  );
}

function unmount(el: Element) {
  const root = mounts.get(el);
  if (!root) return;
  root.unmount();
  mounts.delete(el);
}

declare global {
  interface Window {
    CockpitPdf: { render: typeof render; unmount: typeof unmount };
  }
}

window.CockpitPdf = { render, unmount };
